// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBwjw3eoco7KbSB6_nJ7StFhO3Sdr2ckg',
    appId: '1:578730612078:web:f136f0aaba59f553c71d7f',
    messagingSenderId: '578730612078',
    projectId: 'mark-it-bookmark-app',
    authDomain: 'mark-it-bookmark-app.firebaseapp.com',
    storageBucket: 'mark-it-bookmark-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkxaACIZhOLZQkp-4kZ67cmNQYFJYl0y8',
    appId: '1:578730612078:android:5fcdfcb569cf8082c71d7f',
    messagingSenderId: '578730612078',
    projectId: 'mark-it-bookmark-app',
    storageBucket: 'mark-it-bookmark-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcIQzTg2VUCcy6lUEx6_GUORj6tZTmUUk',
    appId: '1:578730612078:ios:19ef7d15723a0754c71d7f',
    messagingSenderId: '578730612078',
    projectId: 'mark-it-bookmark-app',
    storageBucket: 'mark-it-bookmark-app.firebasestorage.app',
    iosBundleId: 'com.example.markItBookmarkApp',
  );
}
